name: 100% Coverage
on:
  - push

jobs:
  test:
    env:
      MongoDb: mongodb://root:rootpassword@localhost:27017
      DatabaseName: test
    uses: seamuslowry/workflows/.github/workflows/test_python.yml@feature/compose_for_tests
    with:
      compose-file: docker-compose.yml
