name: 100% Coverage
on:
  - push

jobs:
  test:
    uses: seamuslowry/workflows/.github/workflows/test_python.yml@feat/working_directory
    with:
      compose-file: docker-compose.test.yml
      path: api
