name: 100% Coverage
on:
  - push

jobs:
  test:
    uses: seamuslowry/workflows/.github/workflows/test_python.yml@main
    with:
      compose-file: docker-compose.test.yml
      python-version: "3.10"
