name: Deploy to Prod
on:
  push:
    branches:
      - main

jobs:
  tag-new-version:
    uses: seamuslowry/workflows/.github/workflows/tag.yml@main
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}


jobs:
  deploy:
    uses: seamuslowry/workflows/.github/workflows/deploy_python_functions.yml@main
    with:
      name: hundredandten
    secrets:
      azure_publish_profile: ${{ secrets.AZURE_PROD_PUBLISH }}
