name: Deploy to Dev
on:
  push:
    branches-ignore:
      - main

jobs:
  deploy:
    uses: seamuslowry/workflows/.github/workflows/deploy_python_functions.yml@main
    with:
      name: hundredandten
    secrets:
      azure_publish_profile: ${{ secrets.AZURE_DEV_PUBLISH }}
